import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { UserProvider } from "@/services/user.context";
import QueryProvider from "@/services/query.provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gondolkodtato",
  description: "Generated by Gondolkodtato",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-900 text-slate-50`}
      >
        <UserProvider>
          <QueryProvider>
            <Navbar></Navbar>
            <section className="lg:mt-8 mt-6 lg:w-7xl w-full mx-auto lg:p-0 p-4">
              {children}
            </section>
          </QueryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
